image: maven:latest
variables:
  SONAR_TOKEN: $SONAR_TOKEN_PORTFOLIOSERVICE
  SONAR_HOST_URL: "https://sonarcloud.io"
  GIT_DEPTH: 0

sonarcloud-backend-portfolio:
  stage: sonar
  script:
    - cd "${CI_PROJECT_DIR}/backend/portfolioservice"
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=com.dossier.portfolioservice -Dsonar.login=$SONAR_TOKEN_PORTFOLIOSERVICE -Dsonar.organization=zemoso-int
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - dev
    - main
